# Generated by Django 3.1.2 on 2020-10-10 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201005_1802'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together={('title', 'date')},
        ),
    ]
