# Generated by Django 3.1.2 on 2020-10-05 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201005_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='sub_topics',
        ),
        migrations.AddField(
            model_name='topic',
            name='parent_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic'),
        ),
    ]
