# Generated by Django 3.1.2 on 2020-10-10 01:58

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20201009_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='files/photos'), upload_to=''),
        ),
    ]
